gstbilling/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gstbillingapp.urls')),
    path('', include('social_django.urls', namespace='social'))
]

gstbillingapp/urls.py
from django.urls import path
from django.urls import include

from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),

    path('invoices/new', views.invoice_create, name='invoice_create'),
    path('invoices/delete', views.invoice_delete, name='invoice_delete'),

    path('login', views.login_view, name='login_view'),
    path('signup', views.signup_view, name='signup_view'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('invoices', views.invoices, name='invoices'),
    path('invoice/<int:invoice_id>', views.invoice_viewer, name='invoice_viewer'),

    path('customers', views.customers, name='customers'),
    path('customers/add', views.customer_add, name='customer_add'),
    path('customers/edit/<int:customer_id>', views.customer_edit, name='customer_edit'),
    path('customers/delete', views.customer_delete, name='customer_delete'),
    path('customersjson', views.customersjson, name='customersjson'),

    path('products', views.products, name='products'),
    path('products/add', views.product_add, name='product_add'),
    path('products/edit/<int:product_id>', views.product_edit, name='product_edit'),
    path('products/delete', views.product_delete, name='product_delete'),
    path('productsjson', views.productsjson, name='productsjson'),

    path('inventory', views.inventory, name='inventory'),
    path('inventory/<int:inventory_id>', views.inventory_logs, name='inventory_logs'),
    path('inventory/<int:inventory_id>/addupdate', views.inventory_logs_add, name='inventory_logs_add'),

    path('books', views.books, name='books'),
    path('books/<int:book_id>', views.book_logs, name='book_logs'),
    path('books/<int:book_id>/addupdate', views.book_logs_add, name='book_logs_add'),


    path('profile', views.user_profile, name='user_profile'),
    path('profile/edit', views.user_profile_edit, name='user_profile_edit'),
    path('TAbills', views.TAbills, name='TAbills'),
    path('DAbills', views.DAbills, name='DAbills'),


]

gstbillingapp/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime
# Create your models here.

# ========================== Saas Data models ==================================

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    business_title = models.CharField(max_length=100, blank=True, null=True)
    business_address = models.TextField(max_length=400, blank=True, null=True)
    business_email = models.EmailField(blank=True, null=True)
    business_phone = models.CharField(max_length=20, blank=True, null=True)
    business_gst = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Plan(models.Model):
    plan_name = models.TextField(max_length=20, blank=True, null=True)
    plan_value = models.IntegerField(blank=True, null=True)
    monthly_invoice_limit = models.IntegerField(blank=True, null=True)


class BillingProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, blank=True, null=True, on_delete=models.SET_NULL)
    plan_start_date = models.DateField(blank=True, null=True)
    plan_end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.user.username

# ======================= Invoice Data models =================================

class Customer(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer_name = models.CharField(max_length=200)
    customer_address = models.TextField(max_length=600, blank=True, null=True)
    customer_phone = models.CharField(max_length=14, blank=True, null=True)
    customer_gst = models.CharField(max_length=15, blank=True, null=True)
    def __str__(self):
        return self.customer_name


class Invoice(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    invoice_number = models.IntegerField()
    invoice_date = models.DateField()
    invoice_customer = models.ForeignKey(
        'Customer',
        on_delete=models.SET_NULL,
        null=True
    )
    invoice_json = models.TextField()
    inventory_reflected = models.BooleanField(default=True)
    books_reflected = models.BooleanField(default=True)
    def __str__(self):
        return str(self.invoice_number) + " | " + str(self.invoice_date)


class Product(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product_name = models.CharField(max_length=200)
    product_hsn = models.CharField(max_length=50, null=True, blank=True)
    product_unit = models.CharField(max_length=50)
    product_gst_percentage = models.FloatField()
    product_rate_with_gst = models.FloatField()
    def __str__(self):
        return str(self.product_name)

# ========================= Inventory Data models ====================================
class InventoryLog(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    change = models.IntegerField(default=0)
    CHANGE_TYPES = [
        (0, 'Other'),
        (1, 'Purchase'),
        (2, 'Production'),
        (4, 'Sales'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.product.product_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)

class Inventory(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    current_stock = models.IntegerField(default=0)
    alert_level = models.IntegerField(default=0)
    last_log = models.ForeignKey(InventoryLog, null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.product.product_name

# ========================= Books Data models ======================================

class Book(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    current_balance = models.FloatField(default=1000000)
    last_log = models.ForeignKey('BookLog', null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.customer.customer_name


class BookLog(models.Model):
    parent_book = models.ForeignKey(Book, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    CHANGE_TYPES = [
        (0, 'Paid'),
        (1, 'Purchased Items'),
        (2, 'Sold Items'),
        (4, 'Other'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)
    change = models.FloatField(default=0.0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.parent_book.customer.customer_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)

gstbillingapp/forms.py
from django.forms import ModelForm
from .models import Customer
from .models import Product
from .models import UserProfile
from .models import InventoryLog
from .models import BookLog


class CustomerForm(ModelForm):
     class Meta:
         model = Customer
         fields = ['customer_name', 'customer_address', 'customer_phone', 'customer_gst']


class ProductForm(ModelForm):
     class Meta:
         model = Product
         fields = ['product_name', 'product_hsn', 'product_unit', 'product_gst_percentage', 'product_rate_with_gst']


class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['business_title'].required = True

    class Meta:
        model = UserProfile
        fields = ['business_title', 'business_address', 'business_email', 'business_phone', 'business_gst']


class InventoryLogForm(ModelForm):
    class Meta:
        model = InventoryLog
        fields = ['date', 'change', 'change_type', 'description']


class BookLogForm(ModelForm):
    class Meta:
        model = BookLog
        fields = ['date', 'change', 'change_type', 'description']

gstbillingapp/templates/gstbillingapp/DAbills.html
{% extends "gstbillingapp/base.html" %}


{% load static %}
<!doctype html>

{% block content %}


<H1>DA Bills</H1>

 <!--  Bill details starts from here -->

{% endblock %}

{% block includejs %}
<script src="{% static "gstbillingapp/js/fuse-3.4.6.min.js" %}"></script>
<script src="{% static "gstbillingapp/js/main.js" %}"></script>
<script>	function add() {
	var result = document.getElementById('product').value;
	var result1 = document.getElementById('qty').value;
	var log = document.getElementById('rate').value;


	var table = `<tr>
			<td>${result}</td>
			<td>${result1}</td>
			<td>${log}</td>
			</tr>
				`;
	xaxix.push(log);
	yaxix.push(result1);
	document.getElementById('tbl').innerHTML += table;

}</script>
{% endblock %}

                <!-- Ends here -->

gstbillingapp/templates/gstbillingapp/TAbills.html
{% extends "gstbillingapp/base.html" %}


{% load static %}
<!doctype html>

{% block content %}

<H1>TA bills</H1>


 <!--  Bill details starts from here -->

{% endblock %}

{% block includejs %}
<script src="{% static "gstbillingapp/js/fuse-3.4.6.min.js" %}"></script>
<script src="{% static "gstbillingapp/js/main.js" %}"></script>
<script>	function add() {
	var result = document.getElementById('product').value;
	var result1 = document.getElementById('qty').value;
	var log = document.getElementById('rate').value;


	var table = `<tr>
			<td>${result}</td>
			<td>${result1}</td>
			<td>${log}</td>
			</tr>
				`;
	xaxix.push(log);
	yaxix.push(result1);
	document.getElementById('tbl').innerHTML += table; 

}</script>
{% endblock %}

                <!-- Ends here -->

gstbillingapp/templates/gstbillingapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>

	{% block metatags %}
	{% endblock %}



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">

	<!-- DataTables CSS  -->
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/jquery.dataTables.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/dataTables.bootstrap4.min.css" %}">

	{% block includecss %}
	{% endblock %}

</head>

<body>

	<div class="container">
		<!-- Content here -->

		{% include "gstbillingapp/navbar.html" %}

		{% if error_message %}
		<div class="alert alert-danger" role="alert">
			{{error_message}}
		</div>
		{% endif %}

		{% if success_message %}
		<div class="alert alert-success" role="alert">
			{{success_message}}
		</div>
		{% endif %}

		{% block content %}
		CONTENT BLOCK
		{% endblock %}

	</div>




	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	
	<!-- 	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->
	<script src="{% static "gstbillingapp/js/jquery-3.4.1.min.js" %}"></script>
	<script src="{% static "gstbillingapp/js/popper.min.js" %}"></script>

	<script src="{% static "gstbillingapp/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

	<!-- DataTables  -->
	<script src="{% static "gstbillingapp/DataTables/jquery.dataTables.min.js" %}"></script>


	{% block includejs %}
	{% endblock %}



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159304253-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159304253-1');
</script>



</body>


</html>

gstbillingapp/templates/gstbillingapp/book_logs.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Balance Details</h2>
<hr>
<div class="row">
	<div class="col">
		<h3>Customer: {{book.customer.customer_name}}</h3>
		<h3>Current Balance: {{book.current_balance}}</h3>
	</div>
	<div class="col">
		<a href="{% url 'book_logs_add' book.id %}" id="add_customer_btn"><button type="button" class="btn btn-primary">Add Update</button></a>
	</div>
</div>
<hr>
<table class="table table-hover font-weight-bold" id="inventory-logs-table">
	<thead>
		<tr>
			<th>Date</th>
			<th>Type</th>
			<th>Description</th>
			<th>Change</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for item in book_logs %}
		<tr class="{% if item.change < 0 %}table-danger{% else %}table-success{%endif%}">
			<td>{{item.date}}</td>
			<td>{{item.get_change_type_display}} {% if item.associated_invoice %}<a href="{% url 'invoice_viewer' item.associated_invoice.id %}">[INVOICE]</a>{% endif %}</td>
			<td>{{item.description}}</td>
			<td class="text-right">{{item.change}} &emsp; {{inventory.product.product_unit}}</td>
		{% endfor %}
	</tbody>
</table>




{% endblock %}


{% block includejs %}
<script type="text/javascript">
$(document).ready( function () {
	$('#inventory-logs-table').DataTable({
		"order": [],
		"paging": true,
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/book_logs_add.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Update Book</h2>

<hr>
<div class="row">
	<div class="col">
		<h3>Customer: {{book.customer.customer_name}}</h3>
		<h3>Current Balance: {{book.current_balance}}</h3>
	</div>
</div>


<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Date & Time:</th>
				<td class="form-input-td customer_search_area">{{form.date}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change in balance:</th>
				<td class="form-input-td">{{form.change}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change Type:</th>
				<td class="form-input-td">{{form.change_type}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Associated Invoice Number:</th>
				<td class="form-input-td"><input type="text" name="invoice_no"></ins></td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Desription:</th>
				<td class="form-input-td">{{form.description}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>

{% endblock %}

gstbillingapp/templates/gstbillingapp/books.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
	<div class="col">
		<h2>Balance</h2>
		<h3>Current Balance: {{book.current_balance}}</h3>
	</div>
</div>

<table class="table table-hover font-weight-bold" id="book-table">
	<thead>
		<tr>
			<th>Customer</th>
			<th>Current Balance</th>
			<th>Last Transaction</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for book in book_list %}
		<tr onclick="window.location='{% url 'book_logs' book.id %}';">
			<td><a href="{% url 'book_logs' book.id %}">{{book.customer.customer_name}}</a></td>
			<td>{{book.current_balance}}</td>
			<td>{{book.last_log}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}


{% block includejs %}
<script type="text/javascript">

$(document).ready( function () {
	$('#book-table').DataTable({
		"order": [],
		"columnDefs": [ {
			"targets": 3,
			"sortable": false,
			"searchable": false
		} ],
		"paging": true
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/customer_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Edit Customer</h2>
<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Customer Name:</th>
				<td class="form-input-td">{{customer_form.customer_name}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Customer Address:</th>
				<td class="form-input-td">{{customer_form.customer_address}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Customer Phone:</th>
				<td class="form-input-td">{{customer_form.customer_phone}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Customer GST:</th>
				<td class="form-input-td" pattern="([A-Za-z0-9]{15})|(^$)">{{customer_form.customer_gst}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>

{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
	<div class="col">
		<h2>Inventory</h2>
	</div>
</div>

<table class="table table-hover font-weight-bold" id="inventory-table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Current Stock</th>
			<th>Last Transaction</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for inventory in inventory_list %}
		<tr onclick="window.location='{% url 'inventory_logs' inventory.id %}';">
			<td><a href="{% url 'inventory_logs' inventory.id %}">{{inventory.product.product_name}}</a></td>
			<td>{{inventory.current_stock}}</td>
			<td>{{inventory.last_log}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}


{% block includejs %}
<script type="text/javascript">

$(document).ready( function () {
	$('#inventory-table').DataTable({
		"order": [],
		"columnDefs": [ {
			"targets": 3,
			"sortable": false,
			"searchable": false
		} ],
		"paging": true
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory_logs.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Inventory Details</h2>
<hr>

<div class="row">
	<div class="col">
		<h3>Product: {{inventory.product}}</h3>
		<h3>Current Stock: {{inventory.current_stock}}</h3>
	</div>
	<div class="col">
		<a href="{% url 'inventory_logs_add' inventory.id %}" id="add_customer_btn"><button type="button" class="btn btn-primary">Add Update</button></a>
	</div>
</div>

<hr>

<table class="table table-hover font-weight-bold" id="inventory-logs-table">
	<thead>
		<tr>
			<th>Date</th>
			<th>Type</th>
			<th>Description</th>
			<th>Change</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for item in inventory_logs %}
		<tr class="{% if item.change < 0 %}table-danger{% else %}table-success{%endif%}">
			<td>{{item.date}}</td>
			<td>{{item.get_change_type_display}} {% if item.associated_invoice %}<a href="{% url 'invoice_viewer' item.associated_invoice.id %}">[INVOICE]</a>{% endif %}</td>
			<td>{{item.description}}</td>
			<td class="text-right">{{item.change}} &emsp; {{inventory.product.product_unit}}</td>
		{% endfor %}
	</tbody>
</table>



{% endblock %}


{% block includejs %}
<script type="text/javascript">
$(document).ready( function () {
	$('#inventory-logs-table').DataTable({
		"order": [],
		"paging": true,
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory_logs_add.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Update Inventory</h2>
<hr>
<div class="row">
	<div class="col">
		<h3>Product: {{inventory.product}}</h3>
		<h3>Current Stock: {{inventory.current_stock}}</h3>
	</div>
	<div class="col">
		<a href="{% url 'inventory_logs_add' inventory.id %}" id="add_customer_btn"><button type="button" class="btn btn-primary">Add Update</button></a>
	</div>
</div>


<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Date & Time:</th>
				<td class="form-input-td">{{form.date}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change in stock:</th>
				<td class="form-input-td">{{form.change}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change Type:</th>
				<td class="form-input-td">{{form.change_type}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Associated Invoice Number:</th>
				<td class="form-input-td"><input type="text" name="invoice_no"></ins></td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Desription:</th>
				<td class="form-input-td">{{form.description}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>

{% endblock %}

gstbillingapp/templates/gstbillingapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'landing_page' %}">GST Billing</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'invoice_create' %}">Billing Details<span class="sr-only">(current)</span></a>
			</li>
			<!-- <li class="nav-item">
				<a class="nav-link" href="{% url 'invoices' %}">Invoices</a>
			</li> -->
			<!-- <li class="nav-item">
				<a class="nav-link" href="{% url 'inventory' %}">Inventory</a>
			</li> -->
			<li class="nav-item">
				<a class="nav-link" href="{% url 'books' %}">Balance</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'customers' %}">Customers</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'products' %}">Products</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user_profile' %}">Profile</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
			</li>
			{% endif %}
		</ul>
	</div>
</nav>

gstbillingapp/templates/gstbillingapp/print_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">

	<!-- DataTables CSS  -->
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/jquery.dataTables.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/dataTables.bootstrap4.min.css" %}">

	{% block includecss %}
	{% endblock %}

</head>

<body>

	{% include "gstbillingapp/navbar.html" %}





		{% block content %}
		CONTENT BLOCK
		{% endblock %}





	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static "gstbillingapp/js/jquery-3.4.1.min.js" %}"></script>
	<script src="{% static "gstbillingapp/js/popper.min.js" %}"></script>

	<script src="{% static "gstbillingapp/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

	<!-- DataTables  -->
	<script src="{% static "gstbillingapp/DataTables/jquery.dataTables.min.js" %}"></script>

	{% block includejs %}
	{% endblock %}

</body>


</html>

gstbillingapp/templates/gstbillingapp/product_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}

<h2>Edit Product</h2>
<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Product Name:</th>
				<td class="form-input-td">{{product_form.product_name}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">HSN:</th>
				<td class="form-input-td">{{product_form.product_hsn}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Product Unit:</th>
				<td class="form-input-td">{{product_form.product_unit}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">GST %:</th>
				<td class="form-input-td">{{product_form.product_gst_percentage}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Rate with GST:</th>
				<td class="form-input-td">{{product_form.product_rate_with_gst}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>
{% endblock %}

gstbillingapp/templates/gstbillingapp/user_profile_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}

<h2>Edit Profile</h2>
<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Business Name:</th>
				<td class="form-input-td customer_search_area">{{user_profile_form.business_title}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Address:</th>
				<td class="form-input-td">{{user_profile_form.business_address}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Email:</th>
				<td class="form-input-td">{{user_profile_form.business_email}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Phone:</th>
				<td class="form-input-td">{{user_profile_form.business_phone}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">GST:</th>
				<td class="form-input-td" pattern="([A-Za-z0-9]{15})|(^$)">{{user_profile_form.business_gst}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>

{% endblock %}